AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  animal-classifier

  SAM Template for animal-classifier

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ClassifierFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole

  ClassifierApiPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - ClassifierApi
      - ClassifierFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ClassifierFunction
      Principal: apigateway.amazonaws.com

  ClassifierApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: AWS_IAM

  ClassifierFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: classifier/
      Handler: app.lambda_handler
      Runtime: python3.7
      Role: !GetAtt ClassifierFunctionRole.Arn
      Events:
        Animal:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /animal
            Method: get
            RestApiId: !Ref ClassifierApi

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ClassifierApi:
    Description: "API Gateway endpoint URL for Prod stage for Classifier function"
    Value: !Sub "https://${ClassifierApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/animal/"
  ClassifierFunction:
    Description: "Classifier Lambda Function ARN"
    Value: !GetAtt ClassifierFunction.Arn
  ClassifierFunctionIamRole:
    Description: "Implicit IAM Role created for Classifier function"
    Value: !GetAtt ClassifierFunctionRole.Arn
