AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  animal-classifier

  SAM Template for animal-classifier

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ClassifierApi:
    Type: AWS::Serverless::Api
    Properties:
      BinaryMediaTypes:
        - image~1*
      Cors:
        AllowMethods: "'POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,x-requested-with'"
        # AllowOrigin: "'https://tarunb12.github.io'"
        AllowOrigin: "'*'"
      StageName: Prod

  ClassifierFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: classifier/
      Handler: animal.lambda_handler
      Runtime: python3.7
      Layers:
        - !Ref TFLiteLayer
      Events:
        Animal:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /animal
            Method: post
            RestApiId: !Ref ClassifierApi

  TFLiteLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: tflite-runtime-layer
      Description: Lambda layer containing api dependencies [tflite_runtime, numpy]
      ContentUri: dependencies/lib.zip
      CompatibleRuntimes:
        - python3.7

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ClassifierApi:
    Description: "API Gateway endpoint URL for Prod stage for Classifier function"
    Value: !Sub "https://${ClassifierApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/animal/"
  ClassifierFunction:
    Description: "Classifier Lambda Function ARN"
    Value: !GetAtt ClassifierFunction.Arn
  ClassifierFunctionIamRole:
    Description: "Implicit IAM Role created for Classifier function"
    Value: !GetAtt ClassifierFunctionRole.Arn
