export const CATS = [
  'american bobtail',
  'american curl',
  'american shorthair',
  'american wirehair',
  'applehead siamese',
  'balinese',
  'bengal',
  'birman',
  'bombay',
  'british shorthair',
  'burmese',
  'burmilla',
  'calico',
  'canadian hairless',
  'chartreux',
  'chausie',
  'chinchilla',
  'cornish rex',
  'cymric',
  'devon rex',
  'dilute calico',
  'dilute tortoiseshell',
  'domestic long hair',
  'domestic medium hair',
  'domestic short hair',
  'egyptian mau',
  'exotic shorthair',
  'extra-toes cat - hemingway polydactyl',
  'havana',
  'himalayan',
  'japanese bobtail',
  'javanese',
  'korat',
  'laperm',
  'maine coon',
  'manx',
  'munchkin',
  'nebelung',
  'norwegian forest cat',
  'ocicat',
  'oriental long hair',
  'oriental short hair',
  'oriental tabby',
  'persian',
  'pixiebob',
  'ragamuffin',
  'ragdoll',
  'russian blue',
  'scottish fold',
  'selkirk rex',
  'siamese',
  'siberian',
  'silver',
  'singapura',
  'snowshoe',
  'somali',
  'sphynx - hairless cat',
  'tabby',
  'tiger',
  'tonkinese',
  'torbie',
  'tortoiseshell',
  'turkish angora',
  'turkish van',
  'tuxedo',
  'york chocolate',
] as const;

export type CatBreed = typeof CATS[number];